//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmstuCSharpBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public System.Guid ID { get; set; }
        public string Message { get; set; }
    }
}
