//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmstuCSharpBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public System.Guid ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Group { get; set; }
        public string FileName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
