//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotControlPanel.ControlReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlReference.IControlService")]
    public interface IControlService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlService/Query", ReplyAction="http://tempuri.org/IControlService/QueryResponse")]
        string Query();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlService/StartTrace", ReplyAction="http://tempuri.org/IControlService/StartTraceResponse")]
        void StartTrace(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlService/StopTrace", ReplyAction="http://tempuri.org/IControlService/StopTraceResponse")]
        void StopTrace();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlServiceChannel : BotControlPanel.ControlReference.IControlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlServiceClient : System.ServiceModel.ClientBase<BotControlPanel.ControlReference.IControlService>, BotControlPanel.ControlReference.IControlService {
        
        public ControlServiceClient() {
        }
        
        public ControlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Query() {
            return base.Channel.Query();
        }
        
        public void StartTrace(string ip) {
            base.Channel.StartTrace(ip);
        }
        
        public void StopTrace() {
            base.Channel.StopTrace();
        }
    }
}
